name: Django CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4

    - name: Docker Compose Up
      run: docker compose up -d
      env:
        SECRET_KEY: 'secret'
        POSTGRES_NAME: 'postgres'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_HOST: 'db'
        POSTGRES_PORT: '5432'
        CELERY_BROKER_URL: 'amqp://rabbit:5672/'
        AWS_ACCESS_KEY_ID: 'temp'
        AWS_SECRET_ACCESS_KEY: 'temp'
        AWS_DEFAULT_REGION: 'us-east-1'
        AWS_ENDPOINT_URL: 'http://localstack:4566/'
        AWS_EMAIL_SOURCE: 'mihail.usmanov3@gmail.com'
        AWS_BUCKET_NAME: 'bucket'

    - name: Make migrations
      run: docker exec innotter-web-1 pipenv run ./manage.py makemigrations
    - name: Migrate
      run: docker exec innotter-web-1 pipenv run ./manage.py migrate
    - name: Check Tests
      run: docker exec innotter-web-1 pipenv run coverage run ./manage.py test
    - name: Check Test Coverage
      run: docker exec innotter-web-1 pipenv run coverage report --fail-under=90
